apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autofix-dojo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "autofix-dojo.labels" . | nindent 4 }}
data:
  DEFECTDOJO_URL: {{ .Values.defectdojo.url | quote }}
  DEFECTDOJO_PRODUCT_ID: {{ .Values.defectdojo.productId | quote }}
  GIT_REPO_PATH: {{ .Values.git.repoPath | quote }}
  GIT_REMOTE: {{ .Values.git.remote | quote }}
  GIT_MAIN_BRANCH: {{ .Values.git.mainBranch | quote }}
  GIT_PLATFORM: {{ .Values.git.platform | quote }}
  SLO_DB_PATH: {{ .Values.slo.dbPath | quote }}
  HELM_SCAN_PATH: {{ .Values.helm.scanPath | quote }}
  HELM_SCAN_INTERVAL: {{ .Values.helm.scanInterval | quote }}
